name: sos10
description: Semana Omnistack 10 - Backend
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  postgres: ^1.0.0
  http: ^0.12.0+4

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0